%%
ieInit;

%%
lensName = 'dgauss.22deg.3.0mm.json';
%% Generate ray pairs
maxRadius = 0.6;
minRadius = 0;
offset=0.1;

[iRays, oRays, planes, nanIdx, pupilPos, pupilRadii,lensThickness] = lensRayPairs(lensName, 'visualize', false,...
    'n radius samp', 50, 'elevation max', 40,...
    'nAzSamp',50,'nElSamp',50,...
    'reverse', true,...
    'max radius', maxRadius,...
    'min radius', minRadius,...
    'planeOffset',offset);


%% Poly fit
polyDeg = 5
fpath = fullfile(ilensRootPath, 'local', 'polyjson_test.json');
[polyModel, jsonPath] = lensPolyFit(iRays, oRays,'planes', planes,...
    'visualize', true, 'fpath', fpath,...
    'maxdegree', polyDeg,...
    'pupil pos', pupilPos,...
    'pupil radii', pupilRadii,'lensthickness',lensThickness);
