clear; close all;


%% Lens name and properties
lensName='pixel4a-rearcamera-ellipse'
filmdistance_mm=0.464135918
offset_sensorside=filmdistance_mm;
offset_objectside=1.48002192; %%mm
lensThickness=4.827;

%% Load input output rays 
% load data generated by ZEMAX
X=dlmread('Gout-P4Ra_20111103.txt','\s',1);

% Extract input and output rays
iRays=X(:,[3 5 6]);
oRays=X(:,[8 9 10 11 12 13]);


%% RTF generation options
polyDeg = 4
outputDir = fullfile(piRootPath, 'data/lens/');
outputDir='./'
visualize=true;

%% generateRTF
rtf=generateRTFfromIO(lensName,iRays,oRays,offset_sensorside,offset_objectside,lensThickness,'outputdir',outputDir,'visualize',visualize)
